### ISSUE TITLE
Works fine locally, but doesn't work when deployed to Meteor.com

### ISSUE THREAD

**Issue by adriangrantdotorg** [halunka/meteor-videobackground#3]
Thanks for putting this together!

Quick question from a newbie Meteor developer: locally the app is running fine but when deployed [http://zen-to-do.meteor.com/](http://zen-to-do.meteor.com/) the background video doesn't work.  Not even the poster image appears though it's viewable from [http://zen-to-do.meteor.com/img/clouds.jpg](http://zen-to-do.meteor.com/img/clouds.jpg). 

Any clue what's up?

**Comment by halbgut** [comment]
Hi @adriangrantdotorg 

Sorry for the slow response; I was asleep. In your deployed app all the JS is minified, so I can't tell what's wrong from that. To find the problem I'd need some source-code. At least the relevant HTML and JS. Could you post that here?

**Comment by adriangrantdotorg** [comment]
Thanks @Kriegslustig here's a link to the repo [https://github.com/adriangrantdotorg/Zen-To-Do](https://github.com/adriangrantdotorg/Zen-To-Do)

**Comment by halbgut** [comment]
Ah, well your problem is simple; you added the `videobackground` to the `task` template. That means, that for every task you add  background is displayed. When you load the app on `zen-to-do.meteor.com`, there aren't any task; so no background is displayed. When you then add a task, the background will be displayed.

So you'll need to move `{{ > videobackground vbgOptions }}` into `<body>` and move the helper declaration (`vbgOptions () {...}`) up into `Template.body.helpers`.

Hope that helps :)

**Comment by adriangrantdotorg** [comment]
_slaps head_
Of course! Thanks for the heads up! I fixed it and will close this issue
